enum BATTLE_TYPE_EVENT {
    MATCH_FOUND = "MATCH_FOUND",
    MATCH_STATUS_UPDATE = "MATCH_STATUS_UPDATE",
    MATCHMAKING_FAILED = "MATCHMAKING_FAILED",
    MATCH_CANCELLED = "MATCH_CANCELLED",
}

export const BATTLE_STATUS = {
    BATTLE_TYPE_EVENT
}