export enum RewardSourceType {
  REWARD_SERVICE = 'REWARD_SERVICE',
  LESSON = 'LESSON',
  DAILY_REQUEST = 'DAILY_REQUEST',
  ATTENDANCE = 'ATTENDANCE',
  SEASON_REWARD = 'SEASON_REWARD',
  ADMIN_ADJUST = 'ADMIN_ADJUST',
  OTHER = 'OTHER',
  ACHIEVEMENT_REWARD = 'ACHIEVEMENT_REWARD',
  EXERCISE = 'EXERCISE',
}

