export enum TestStatus {
    PLACEMENT_TEST_DONE = "PLACEMENT_TEST_DONE",
    SUBSCRIPTION_TEST = "SUBSCRIPTION_TEST",
    MATCH_TEST = "MATCH_TEST",
    QUIZ_TEST = "QUIZ_TEST",
    REVIEW_TEST = "REVIEW_TEST",
    PRACTICE_TEST = "PRACTICE_TEST",
    READING_TEST = "READING_TEST",
    LISTENING_TEST = "LISTENING_TEST",
    SPEAKING_TEST = "SPEAKING_TEST",
  }