export enum USER_ACHIEVEMENT_STATUS {
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED_NOT_CLAIMED = 'COMPLETED_NOT_CLAIMED',
    CLAIMED = 'CLAIMED'
}

export const USER_ACHIEVEMENT = {
    USER_ACHIEVEMENT_STATUS
}